### ISSUE TITLE
ActiveJobs are all wrapped into one unique report

### ISSUE THREAD

**Issue by rnaud** [appsignal/appsignal#25] opened 2014-11-26 21:51 UTC
Hey guys!

On our AppSignal reports, all of our Sidekiq jobs are being reported under an ActiveJob wrapper:
ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper

Any way to fix that?

Arnaud

**Comment by fwl** [comment] 2015-02-13 05:38
Hello,

Is this still the case or has it been fixed since?

Thank you.

**Comment by thijsc** [comment] 2015-05-04 10:04
It looks like this issue was caused by the way Sidekiq integrates with ActiveJob. They've now fixed this in 3.3.4:

`Improved ActiveJob integration - Web UI now shows ActiveJobs in a nicer format and job logging shows the actual class name, requires Rails 4.2.2+ [#2248, #2259]`

https://github.com/mperham/sidekiq/blob/master/Changes.md

Could you try that version of Sidekiq?

**Comment by fwl** [comment] 2015-06-25 18:07
@thijsc I will, thank you for pointing this out!

**Comment by scottrobertson** [comment] 2015-07-06 12:40
It's doing the same for DelayedJob too

**Comment by wvengen** [comment] 2015-09-18 06:35
I'm working on a Que adapter and am wondering how to fix this ActiveJob issue. It looks like Sidekiq and DelayedJob integrate with ActiveJob for display purposes, if I'm reading the appsignal source correctly, but how to do that for ActiveJob backends that don't have this feature?

```ruby
cls = args.last['job_class'] if cls == "ActiveJob::QueueAdapters::QueAdapter::JobWrapper"
```

in an integration might work, but I wonder how a more general solution would look like.

Also, ideally I'd like to see the actual ActiveJob info in the action arguments (incl. a mention of the JobWrapper class), but have Appsignal split jobs by ActiveJob's class name. Not sure how that would fit in, though.

**Comment by matsimitsu** [comment] 2015-09-19 11:24
Hi @wvengen do you have an example/code of your Que adapter? I can take a look and see how best to support AppSigal for it :)

**Comment by wvengen** [comment] 2015-09-19 16:22
@matsimitsu sure, feel free to participate in #70. Thanks!

**Comment by thijsc** [comment] 2016-02-11 09:20
We've greatly improved the ActiveJob integration in 1.1, which is now in beta. Could you try that version @rnaud?

**Closed** 2016-03-15 10:43 UTC
Labels: bug
